### PR TITLE
fixed json for thermal foundation and added all buildcraft stuff

### PR DESCRIPTION
**Pull request by Eleiyas**
fixed a couple of json files for buildcraft (dyes now pull from soartex)

added all I had for buildcraft

### CODE REVIEW

**Comment by artdude543** [comment]
Sorry for the delay on this one. Is this still valid/working, so I can pull this into master?

**Comment by Eleiyas** [comment]
> Sorry for the delay on this one. Is this still valid/working, so I can pull this into master?

THE LORD PRAISES US!!!

Yep it's still working and please, please don't disappear again :P I literally have 99%'ed Mekanism textures too :)

**Comment by artdude543** [comment]
Sweet; My work has taken new heights so I'll vanish a fair amount, and working from home is making our life fun right now ;)

**Comment by Eleiyas** [comment]
> Sweet; My work has taken new heights so I'll vanish a fair amount, and working from home is making our life fun right now ;)

While you're here, is there any chance I can "take command" of this GitHub? I know I'm not an artist, but I have done so much work for this pack and it's... well, a bit of a drag having to wait up to 3 months for stuff to get pushed :/

**Comment by artdude543** [comment]
This would require me getting the internal team to talk about this; but I'll try to make myself more around to get things pushed.

I also need to find time to bring back the server which pushed the files to Curse for us; with changes in Twitch/Curse this requires a fair amount of work. But in time it'll get done; sadly with how Fanver was structured internally things will be slow while I work out the kinks in my free time.

**Comment by Eleiyas** [comment]
> This would require me getting the internal team to talk about this; but I'll try to make myself more around to get things pushed.
> 
> I also need to find time to bring back the server which pushed the files to Curse for us; with changes in Twitch/Curse this requires a fair amount of work. But in time it'll get done; sadly with how Fanver was structured internally things will be slow while I work out the kinks in my free time.

Thank you!

I've been sat on so much work (quarantine is good for some things I guess :p )!

**Pull request merged**
