### PR TITLE
Some 1.12 ports

### PR DESCRIPTION
**Pull request by robjw95**
First try using github.  Ported textures to 1.12  Renaming only matching to base jar file

### CODE REVIEW

**Comment by artdude543** [comment]
Renaming is fine but have you tested it all works? Including the GUI's? Most mods have chanced them and they need redoing.

**Comment by robjw95** [comment]
Thanks for the advise.  Will recheck to make sure I didn't miss anything
especially the gui.  I did not think to check all of them, only did a
comparsion to the source jar version and renamed only the ones that
appeared to match in shape and slots.  I will let you know later when done
rechecking.

RW

On Wed, Jan 10, 2018 at 7:45 AM, Kieron Richardson <notifications@github.com

**Comment by artdude543** [comment]
We are also in progress of changing how our ores/plates/ingots etc.. work. So any mod with these types will need them removed from the mod itself and switched to using the new system (which I'm still working on)

But you can leave them in and I'll remove them all out when I pass over the mods you have ported. I see a lot of ports you have done (now I'm on a PC) but I'm cautious of using them due to all the mass changes to 1.12 with mods and textures.

But we'll take each mod one by one and check / switch to new ore system and so forth. One of the main reasons the 1.12 port is taking time cos of the tweaks we are doing. Along with TLC to each mod to fix the various issues we have seen in previous ports. It's a massive job xD

**Comment by robjw95** [comment]
I tested and reviewed everything.  Found a few things needing fixes and
updated.  I was planning on trying to Port some more mods but will hold off
for now.  Thanks for the help.  Soartex is the best.
RW

**Comment by robjw95** [comment]
Is there anything I need to do on these still??  If so let me know and I will work on the changes

**Comment by Zyian** [comment]
Is this still up for review?

**Comment by artdude543** [comment]
Okay just gone over the majority of this now, and it looks good! Thanks for the work on this, and I apologise on the delay. 

Will get this merged in and push an update to CF in the next few days.

**Pull request merged**
