### PR TITLE
Mekanism (99%) + Mekanism Tools JSONs

### PR DESCRIPTION
**Pull request by Eleiyas**
99% of Mekanism DONE!

### CODE REVIEW

**Comment by artdude543** [comment]
If possible can you go over the other armours/tools and use the `soartex_base` version(s). Most other metal types should already be on there for you to reference.

**Comment by Eleiyas** [comment]
> If possible can you go over the other armours/tools and use the `soartex_base` version(s). Most other metal types should already be on there for you to reference.

do you mean the actual armour models? 

because as far as I'm aware, they aren't in Soartex_Base as of yet. As for the tools, the only Mekanism tools are JSON files that I already made.

**Comment by artdude543** [comment]
Huh, I swear I pushed the actual model. But I didn't nor have them on this device, I'll get that fixed once I'm back home.

So other than that, if you're happy with the textures and such I can pull this into master now.

**Comment by Eleiyas** [comment]
> Huh, I swear I pushed the actual model. But I didn't nor have them on this device, I'll get that fixed once I'm back home.
> 
> So other than that, if you're happy with the textures and such I can pull this into master now.

I'll see what I can do for the armours, I'll have to add them to Soartex_base.

**Comment by artdude543** [comment]
Nah your all good on that front. That can be tweaked at a later date.

**Comment by Eleiyas** [comment]
> Nah your all good on that front. That can be tweaked at a later date.

Well, although I have the basic knowledge of JSONs and how they work, I don't know how I would get one to work for an armour model.

I was trying to figure it out, but without changing the texture path in the class file itself, I am clueless.

Feel free to merge as-is :) 

I have Extra Utils 2, some Botania and some Thaumcraft to push next ^^

**Pull request merged**
