### PR TITLE
Added support for Nutrition

### PR DESCRIPTION
**Pull request by ThatGravyboat**
Added textures for nutrition button and gui.

### CODE REVIEW

**Comment by ThatGravyboat** [comment]
all fixed. Tell me if theres anything else thats wrong cause im not the best with github.

**Comment by artdude543** [comment]
Awesome all the changes are perfect! Am I going to assume you have tested this in the game? If so could you post a screenshot? I'm not at a PC for a few days so can't test it but if I can see visual confirmation I can then merge it in. Thanks!

**Comment by ThatGravyboat** [comment]
The gui is in a waffle pattern cause the way nutrition does there gui they take 3 parts the the top and bottom and the middle but its in  a small form so when it loads up in the game it copys over and over in the middle so thats why the middle of the gui looks a like a waffle but it makes sense cause the mods about food and it looks like a picnic style of gui

**Comment by artdude543** [comment]
Awesome and it looks great; thanks for the texture support! :)

**Pull request merged**
