### PR TITLE
Gregtech Texture port from 1.7.x to 1.12.x

### PR DESCRIPTION
**Pull request by Ormsher**

### CODE REVIEW

**Comment by artdude543** [comment]
- The modId is incorrect needs to be all lowercase as per specification.
- The mod folder should be `GregTech` to match the mod naming convention.
- All ingots/dusts/gears and generic resources need to be using `soartex_base` as the location for the textures to prevent un-needed duplication.

I have been working on creating all the missing base textures to add to `soartex_base` as we have re-done all the colours/scales for 1.12.x. So until I have completed that part this PR will need to be on hold. Until the base is ready and the first two changes are performed.

But amazing work on the PR/Port! 1.12.x is slow for us as we're revamping and cleaning up all the mess from previous versions.

**Comment by Ormsher** [comment]
Hi. I am quite new to this. I am not sure about soartex_base with GTCE. GTCE automatically colors ingots in the game and the pack creator has to only provide black and white texture.

**Comment by Ormsher** [comment]
Turns out at first I managed to push wrong textures. Good catch. Sorry about that.

**Comment by Ormsher** [comment]
I am done porting from 1.7.x. If there is any changes that you need from my end feel free to message me.

**Comment by leagris** [comment]
> I am done porting from 1.7.x. If there is any changes that you need from my end feel free to message me.

@Ormsher Your commit still contains wrong `GregTech` directory name. Your repository has tow folders, one `Gregtech` and one `GregTech`.  Please fix this (see @artdude543 requested changes)

**Comment by LAGIdiot** [comment]
Is this still a live? Is there anything that I can help with because I would like to see this finished.

**Comment by Shoeboxam** [comment]
I went ahead and merged this PR. Seems that the outstanding issue here is items that are not pulled from base. Perhaps this can be done post-merge if folks are really committed to it. I think the damage of not merging the PR for this long is much greater than potentially accepting some non-base textures. The folder naming was an easy fix to make afterwards. 

@LAGIdiot Long time no see. There's a Discord now ~~

**Comment by LAGIdiot** [comment]
@Shoeboxam It is nice that you remembered old me and sure I will come to hang out on Discord!

**Pull request merged**
