### PR TITLE
Add basic support for LibVulpes

### PR DESCRIPTION
**Pull request by rafasoares**
This adds some ore textures and some base textures for other items in LibVulpes, which is the base mod for Advanced Rocketry.

I was mostly concerned about the ores, since they duplicate other ores like Thermal's copper and tin ores, causing two different textures for what would otherwise be the same ore (and are not trivial to unify using ore dictionary). So I reused the textures from Thermal.

The two novel ores are Dilithium and Rutile. For Dilithium, which is a fictional mineral, I've used the gem base file, since the ore is processed into crystals,  and gave it a pink-ish color. For Rutile I gave it a reddish-brown tint. I realize that real life rutile ore isn't as dark or saturated, but I wanted to differentiate it from iron ore as much as possible.

And, since LibVulpes uses base textures for most of its items (like rods, ingots, dusts, etc.), I went ahead and copied Soartex base's textures where there was one and modified the closest ones I could find where there wasn't.

There are still missing items, but they would require work that is beyond my skills.

C&C welcome. as well as contributions to the PR.

### CODE REVIEW

**Comment by Eleiyas** [comment]
All common ores need to pull from Soartex_Base. 

You need to write json files in either "blockstates" or "models" and set the texture address to Soartex_Base.

This is the case for all of your:
* copper
* tin
* aluminum
etc ores.

Dilithium and Rutile ores can be left as they are however as they are mod-specific.

**Comment by rafasoares** [comment]
Thanks for feedback, @Eleiyas!

> All common ores need to pull from Soartex_Base.
> 
> You need to write json files in either "blockstates" or "models" and set the texture address to Soartex_Base.

I suspected that, but have no experience doing it. I honestly thought you needed the mod to use a block state JSON as well (my reference for that was Thermal)

> P.S: Please be aware that this project is pretty much dead and only gets visited by an "admin" every few months or so :/

That's sad. The texture pack was updated in December on CurseForge, which made me think it was somewhat active.

**Comment by Eleiyas** [comment]
> Thanks for the feedback, @Eleiyas!
> 
> I suspected that, but have no experience doing it. I honestly thought you needed the mod to use a block state JSON as well (my reference for that was Thermal)
> 
> That's sad. The texture pack was updated in December on CurseForge, which made me think it was somewhat active.


Yeah, look at Thermal or Mekanism to get an idea on how blockstates and/or model JSONs work. 

I mean, we might get lucky and get someone to come here to accept all the merge requests, but don't bet on it for a while.

**Comment by rafasoares** [comment]
Okay, I'll take a look into the JSON files while we wait.

**Comment by artdude543** [comment]
Textures look good! Just need the change for the base model/blockstates then this is mergeable. :)

**Comment by rafasoares** [comment]
@artdude543 awesome!

What I don't understand is how to make MC use the resources from model/blockstates JSON files then the mod itself loads directly from texture files.

All examples I see override files that already exist in the mods' resource folders. If you look at the [LibVulpes repo](https://github.com/zmaster587/libVulpes/tree/master/src/main/resources/assets/libvulpes), there is no `blockstates` or `models` folder, only the textures directly.

Is there any documentation about this? Everything I can find is about changing models that are already defined using .json files (like Thermal ores).

**Comment by rafasoares** [comment]
NVM, after a bit of trial and error, I figured it out :)

**Comment by Eleiyas** [comment]
> NVM, after a bit of trial and error, I figured it out :)

some mods are finicky and it depends where the textures are pulled from in the actual $Block.class java files.

some mods have all ingots pulled from a general Ingot.class, which then links to a blockstates .json to tell the mod where all the files are coming from.

other mods have each ingot separately in their own model.json sort of thing...

I'll admit it's hard to tell sometimes :D

**Pull request merged**
