### PR TITLE
JEI texture update

### PR DESCRIPTION
**Pull request by MoJoCreatior**
With the newer versions of JEI, the old textures got broken. 
I used the old textures to remap the images correctly.
I also have a slight tweak on the tab selector. (small arrow pointing down for active tab. 
This isn't the only way to tell the inactive tabs from active tabs. 
active are brighter and slightly bigger than the inactive tab texture. 
Arrow is just something i like the look of.

### CODE REVIEW

**Comment by MoJoCreatior** [comment]
Yeah, It'll take a minute though,
modded minecraft takes forever to load. [o_o] (~290-305 mods)

**Comment by MoJoCreatior** [comment]
Can i edit or change this pull request?
I have to nudge a couple textures by a few pixels.
Here's a screenshot of what it's currently at...

**Comment by artdude543** [comment]
Just upload a change and it will auto update this PR :)

**Comment by MoJoCreatior** [comment]
Here is new screenshot. i nudged the tabs and the left side panel over so they line up a little better. And the recipe container is slightly more defined

**Comment by artdude543** [comment]
Awesome! These are great changes. Thank you for your hard work on this! Will get this pulled and pushed up to Curse in the next day or two 😄

**Comment by MoJoCreatior** [comment]
perfect. thanks
I have a patch for SG Craft as well. Maybe I'll put that together this weekend.

**Pull request merged**
