### PR TITLE
Final Pull Request 22/06/19: BC7, EnderIO, Thermal Expansion, Mekanism + Much More

### PR DESCRIPTION
**Pull request by Eleiyas**
Added in all remaining BC7 textures I had

Added in full Thermal Expansion mod (edited as requested)

### CODE REVIEW

**Comment by Eleiyas** [comment]
so, nearly all the machines and GUIs now work for Thermal Expansion and fit the overall theme of this resource pack. might not be 100% perfect, but it's about what I can manage with my limited skill-set.

I'd say this mod is about 80% done at this point.

still having issues with imported textures from CoFH core, but might just be on my end and has nothing to do with what I've done here.

**Comment by Eleiyas** [comment]
now added what I had for EnderIO mod.

**Comment by Eleiyas** [comment]
Final Update with everything I've added/fixed/downloaded for Soartex 1.12.2.

**Comment by Eleiyas** [comment]
"Fixed" Mekanism textures.
Also includes "alt textures" that I had in my release.
Factories are completely broken as only 3 textures exist per upgrade, although there are actually like 12 different factories per type in the mod now.

**Comment by artdude543** [comment]
None of the mekanism ore, metal blocks, ingots and dusts need textures. They are textured via soartex_base they need removing.

Also at this point this all needs breaking down to separate requests for each mod. All these commits are making it a nightmare to review and comment fixes and/or changes.

**Comment by Eleiyas** [comment]
> None of the mekanism ore, metal blocks, ingots and dusts need textures. They are textured via soartex_base they need removing.
> 
> Also at this point this all needs breaking down to separate requests for each mod. All these commits are making it a nightmare to review and comment fixes and/or changes.

alright.
I'll have to delete my fork and re-start as I've done too much to remember what to undo.

**Pull request closed without merging**
