### PR TITLE
added some textures to binnies extra trees 

### PR DESCRIPTION
**Pull request by davedumas0**
add a few of the missing textures for binnies mods extra trees

### CODE REVIEW

**Comment by ScottDTA** [comment]
Are you planning to do some of the others as well?   If so, I can leave this open for a little while and you can add them to it before I merge it.

**Comment by davedumas0** [comment]
yeah i will attempt it at least and as i said before i aint no artist lol

**Comment by davedumas0** [comment]
added a ceramic block as well also working on soil from binnies botany

**Comment by ScottDTA** [comment]
Looking good.

**Comment by ScottDTA** [comment]
Since I saw you were looking at doing some buildcraft gui's, are these good to merge now?

**Comment by davedumas0** [comment]
yeah

**Comment by davedumas0** [comment]
ill do more but im slow

**Comment by davedumas0** [comment]
how does the engine gui look ?
combustion_engine_gui

**Comment by davedumas0** [comment]
if you have a better BG then ill gladly use that

**Comment by ScottDTA** [comment]
You might check the template repo.

https://github.com/Soartex-Modded/Templates

**Pull request merged**
