### PR TITLE
Update Millénaire Mod Texture

### PR DESCRIPTION
**Pull request by UnknownMaxin**
Hello. This is my first time to update the mod textures I modified. I want to do something for the old mods which have updated to 1.12.2 or the other new versions but Soartex Modded Texture didn't update. Please pull my request. Thank you.

### CODE REVIEW

**Comment by ScottDTA** [comment]
Needs a valid mod.json file added.   Take a look at some of the other mods mod.json files to examples.  This will allow the auto build system to function properly.

**Comment by Shoeboxam** [comment]
Thanks for porting these textures! ❤️

**Comment by UnknownMaxin** [comment]
> Thanks for porting these textures! ❤️

You are welcome. It's a pleasure for me to make textures in Soartex style. ❤️

**Comment by ScottDTA** [comment]
> > Needs a valid mod.json file added. Take a look at some of the other mods mod.json files to examples. This will allow the auto build system to function properly.
> 
> I forgot to upload mod.json yesterday... Now I have re-uploaded this file. In addition, some block's texture are uploaded too:)

Looks good.  Thank you.

**Comment by ScottDTA** [comment]
Let me know when you are good and I can merge it.  Will wait till you are ready.

**Comment by UnknownMaxin** [comment]
> Let me know when you are good and I can merge it. Will wait till you are ready.

You can merge it everytime when you are free. The basic version is okay. Millénaire has so many special textures that I need a long time to think about how to make the textures of other blocks & items in Soartex style. Although this mod texture pack is WIP, players can have excellent experience when they play Millénaire mod with this texture packs.

**Comment by UnknownMaxin** [comment]
> Let me know when you are good and I can merge it. Will wait till you are ready.

I just found some error in a texture and I fixed it immediately... Now Millénaire Pack is already preliminarily completed:) 
And a new mod texture is added.

**Pull request merged**
